### ISSUE TITLE
Decide on format for ReadMe page

### ISSUE THREAD

**Issue by AnneCarpenter** [czi-hca-comp-tools/easy-data#4]
I was a bit overwhelmed to see a sort of full-page entry for the first project listed. Once we have 20+ benchmarks listed here it's going to be pretty unwieldy.

Could we perhaps have entries trimmed down (like, to a single paragraph as for the first example), with the beautiful instructions for use in a separate file for each dataset?

tabula muris (URL)
Tabula Muris contains about 100,000 cells from 20 organs and tissues in mouse. The study is sex-balanced, with four male and four female mice. The organs included are skin, fat, mammary gland, heart, bladder, brain, thymus, spleen, kidney, limb muscle, tongue, marrow, trachea, pancreas, lung, large intestine, and liver. Many of these organs were processed using two methods: SMART-seq2 on FACS-sorted cells and microfluidic droplets from 10X Genomics.

**Comment by batson** [comment]
Great point, @AnneCarpenter. We broke each entry out into it's own file now (in `datasets/`).

A minimal record for each dataset on the front page might be helpful too, how much info would you want to see?

**Comment by AnneCarpenter** [comment]
I like how it looks now! I'm not the one to ask about minimal records (I'd vote none but I'm not an immediate data consumer, just a PI!).
